from enum import Enum


class TimeseriesIngestErrorCode(str, Enum):
    UNKNOWN_SITE = "UNKNOWN_SITE"
    UNKNOWN_METER = "UNKNOWN_METER"
    ORG_MISMATCH = "ORG_MISMATCH"
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    INVALID_VALUE = "INVALID_VALUE"
    INVALID_UNIT = "INVALID_UNIT"
    DUPLICATE_IDEMPOTENCY_KEY = "DUPLICATE_IDEMPOTENCY_KEY"
    INTERNAL_ERROR = "INTERNAL_ERROR"
